### ISSUE TITLE
buttons in firefox aren't visible

### ISSUE THREAD

**Issue by agauniyal** [codrops/DistortedButtonEffects#1]
but can be seen in the demo hosted on codrops article :confused:

**Comment by botelho** [comment]
I think you need to run it in a server environment.

**Comment by agauniyal** [comment]
what do you mean by server environment? This was a html-css-svg-js combo I guess? It works in chrome as intended.

**Comment by Grsmto** [comment]
Can you detail more the issue? Buttons are not visible at all or they just don't have the effect?
If they don't have the effect it may be due to the way Firefox handle the filter url path. As suggested it should work when you serve the file from a server (not simply double-click on the index.html file but serve it with php, node or whatever).

**Comment by agauniyal** [comment]
Ah, I never knew there was such a requirement.
